
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 01 11:10:50 BRT 2018
//----------------------------------------------------

package ExemploCUP;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int INTEIRO = 10;

    /**
     *
     */
    public static final int PROGRAMA = 2;
  public static final int TIPO_INTEIRO = 5;
  public static final int INICIO = 3;
  public static final int PTVG = 7;
  public static final int EOF = 0;
  public static final int FIM = 4;
  public static final int TIPO_CHAR = 6;
  public static final int ERRO = 1;
  public static final int SIMBOLO_ATRIB = 8;
  public static final int VARIAVEL = 11;
  public static final int CHAR = 9;
}

